# CONFIG ENTRIES
CURRENT_DATA_DELTA_TABLE_NAME = "CURRENT_DATA_DELTA_TABLE_NAME"
DELTA_SRC = "DELTA_SRC"
KAFKA_SERVER = "KAFKA_SERVER"

# CONFIG VALUES
CURRENT_DATA = "current_data"
DELTA_LOCATION = "delta/"
KAFKA_SERVER_NAME = "localhost:9092"
